# this code was auto generated by pfn

class UnmatchedError(Exception):
	pass

class ArgcountError(Exception):
	pass

def __pfn_call(p, args):
	result=None
	broke=False
	for f in p:
		try:
			result=f(*args)
		except (UnmatchedError, ArgcountError):
			continue
		broke=True

		break
	if not broke:
		raise Exception('no matching function')

	return result
import sys , random , pygame , os 
from SimpleDrawEngine import * 
from astronauts import * 
def pfn_limpaTela(*args):
	if len(args) < 0:
		raise ArgcountError('too few arguments for function limpaTela')
	if (os.name == "nt"):
		os.system("cls")
		return None
	
	os.system("clear")

__pfn_call([pfn_limpaTela], [])
def pfn_main(*args):
	if len(args) < 2:
		raise ArgcountError('too few arguments for function main')
	color = args[0]
	name = args[1]
	pygame.init()
	N=200
	white=(255,255,255)
	black=(0,0,0)
	red=(255,0,0)
	largura=800
	altura=600
	screen=pygame.display.set_mode((largura,altura))
	caption=pygame.display.set_caption("ALPHA")
	stars=[[random.randint(0,largura),random.randint(0,altura)] for _ in range(N)]
	big_stars=[[random.randint(0,largura),random.randint(0,altura)] for _ in range(N)]
	void_sound=pygame.mixer.Sound("sound.ogg")
	void_sound.play(-1)
	vote_typing_sound=pygame.mixer.Sound("vote.ogg")
	impostor_sound=pygame.mixer.Sound("impostor.ogg")
	clock=pygame.time.Clock()
	file=color
	test=45
	pos_x=-360
	vx=10
	angle=0
	player=Player(screen,("characters/" + file + ".png"),(0,0),angle,pos_x)
	texto=Text(24,False,(255,255,255),(0,0),screen)
	impostor=random.choice([True,False])
	final_string=""
	if (name != ""):
		text=list(f"{name} was The Impostor") if impostor else list(f"{name} was not The Impostor")
	else:
		text=list(f"{file} was The Impostor") if impostor else list(f"{file} was not The Impostor")
	
	text_complete=False
	counter=-25.0
	i=0
	while True:
		clock.tick(30)
		for event in pygame.event.get():
			if (event.type == pygame.QUIT):
				pygame.quit()
			
			if ((event.type == pygame.KEYDOWN) and (event.key == pygame.K_ESCAPE)):
				pygame.quit()
			
		
		angle=(angle + 5)
		screen.fill(black)
		counter=(counter + 0.35) if (not text_complete) else counter
		if ((counter >= 1) and (not text_complete)):
			final_string=(final_string + text[i])
			counter=0
			i=(i + 1)
			if (len(final_string) == 1):
				vote_typing_sound.play(-1)
			
			if (len(final_string) == len(text)):
				text_complete=True
				vote_typing_sound.stop()
				if impostor:
					impostor_sound.play()
				
			
		
		texto.draw(final_string,((largura / 2),(altura / 2)))
		for star in stars:
			Rect(screen,white,(star[0],star[1],2,2))
			star[0]=(star[0] - 0.5) if ((star[0] - 0.5) < 0) else largura
		
		for big_star in big_stars:
			Circle(screen,white,(big_star[0],big_star[1]),3)
			if (big_star[0] < 0):
				big_star[0]=largura
			
		
		player.move(vx)
		player.animation(angle)
		pos_x=(pos_x + vx)
		vx=(vx - 0.035)
		if (vx < 0):
			vx=0
		
		pygame.display.update()
	
	pygame.quit()

